language: python
python:
  - "2.7"
  - "3.5"

sudo: false
# dist: precise
# group: edge

notifications:
  slack: lisvai:SgdQxglgGWYCyiAAWa3aU5Pg

before_install:
  # - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip nose numpy scipy scikit-learn matplotlib cvxopt
  - source activate test-environment
  - pip install codecov pep8 python-coveralls codacy-coverage

script:
  - nosetests --with-coverage --cover-erase --logging-level=INFO
  - coverage xml
  

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
  - codecov
  - export CODACY_PROJECT_TOKEN="21b6c8e9b7334f45a1d09132194528f8"
  - python-codacy-coverage -r coverage.xml
