name: Test-and-Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-lint:
    name: test-py-${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel flake8 coverage
          pip install -r requirements.txt
      - name: Run tests
        shell: bash
        run: |
          nosetests
          coverage xml
          coveralls --config_file .coveragerc
          codecov
          python-codacy-coverage -r coverage.xml

#   - name: Run linting
#     shell: bash
#     run: |
#       flake8
